-- Completa el catalogo de clientes (cat_clientes) con la lista
-- maestra de facturacion 'Clientes_2026.xlsx' (72 registros).
--
-- 1) ACTUALIZA los clientes ya existentes (importados antes desde
--    PRECIO_PRENDA_CLIENTE.xlsx, solo tenian nombre_comercial) con
--    razon social, RFC, direccion, telefono y correo -- coincidencia
--    exacta por 'clave' contable. Usa COALESCE: si el campo ya tiene
--    un valor capturado a mano, NO lo pisa.
-- 2) DA DE ALTA los clientes que no tienen coincidencia exacta,
--    usando su razon social como nombre_comercial (no hay una
--    'clave' o nombre comercial corto confiable para inventarles
--    uno) -- se puede renombrar despues desde Catalogos > Clientes.
--
-- Idempotente: se puede re-ejecutar sin duplicar ni perder datos.

-- =========================================================================
-- 1) ACTUALIZAR clientes existentes (23)
-- =========================================================================

UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Administradora De Hoteles Grt Sa De Cv'), `rfc` = COALESCE(`rfc`, 'AHG130507626'), `direccion` = COALESCE(`direccion`, 'Avenida Andrés García Lavín número 298, Centro Comercial City 32 montebello'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'carlos.maas@caminoreal.com;karla.poot@caminoreal.com;maria.salazar@caminoreal.com') WHERE `nombre_comercial` = 'Camino Real';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Administradora Gran Hotel Sa De Cv'), `rfc` = COALESCE(`rfc`, 'AGH120423GY8'), `direccion` = COALESCE(`direccion`, 'Calle 60 #496, entre las calles 59 y 61, Colonia Centro,'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'elgranhotel@hotmail.com') WHERE `nombre_comercial` = 'Gran Hotel';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Avsa Interlog Sa De Cv'), `rfc` = COALESCE(`rfc`, 'AIN190926B52'), `direccion` = COALESCE(`direccion`, 'Calle 59 #500 por 60, esquina con el Parque Hidalgo, en el Centro Histórico'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'facturascaribe@hotmail.com;miguel.cendon@corpover.mx') WHERE `nombre_comercial` = 'Caribe';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Ccmanagement Sa De Cv'), `rfc` = COALESCE(`rfc`, 'TRT130628DD3'), `direccion` = COALESCE(`direccion`, 'Calle 55 número 516, entre calles 62 y 64, Colonia Centro'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'merida@coquicoqui.com;facturacion@coquicoqui.com') WHERE `nombre_comercial` = 'Coqui';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Centro Deportivo Bancario De Yucatan'), `rfc` = COALESCE(`rfc`, 'CDB410804KWA'), `direccion` = COALESCE(`direccion`, 'Avenida Correa Racho, Predio 10016. Mérida. C.P. 98453.'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'contabilidad@bancarios.com.mx;proveedores@bancarios.com.mx') WHERE `nombre_comercial` = 'Bancarios';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Climbe'), `rfc` = COALESCE(`rfc`, 'CLI120123Q15'), `direccion` = COALESCE(`direccion`, 'Prolongación Paseo de Montejo 481, Fraccionamiento Montejo'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'facturas@hoteldelfina.com.mx') WHERE `nombre_comercial` = 'Delfina';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Corporativo Palacio Maya'), `rfc` = COALESCE(`rfc`, 'CPM100519E79'), `direccion` = COALESCE(`direccion`, 'Calle 62 #327 por 37 y 39, Centro, C.P. 97000'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, NULL) WHERE `nombre_comercial` = 'Palacio Maya';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Gabriela Yasmine Quiñones Habib'), `rfc` = COALESCE(`rfc`, 'QUHG7909241J5'), `direccion` = COALESCE(`direccion`, 'Calle 64 #539, Centro, C.P. 97000'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'hotelelcaminante@hotmail.com') WHERE `nombre_comercial` = 'Caminante';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Hauz Complex'), `rfc` = COALESCE(`rfc`, 'HCO181213C92'), `direccion` = COALESCE(`direccion`, 'Calle 66 #593 barrio ermita'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'cigno.adm@outlook.es;gerencia@cignohotel.com') WHERE `nombre_comercial` = 'Cigno';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Hotel Hacienda Merida S De Rl De Cv'), `rfc` = COALESCE(`rfc`, 'HHM0701234G1'), `direccion` = COALESCE(`direccion`, 'Calle 62 #439 por 51 y 53, Col. Centro'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'alex@hotelhaciendamerida.com;info@hotelhaciendamerida.com') WHERE `nombre_comercial` = 'Hacienda';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Lowellcare Sa De Cv'), `rfc` = COALESCE(`rfc`, 'LOW140704LPA'), `direccion` = COALESCE(`direccion`, 'CALLE 62 POR 55 Y 57 #466 cebtro'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'proveedores@mugy.com.mx') WHERE `nombre_comercial` = 'Museo';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Mancover'), `rfc` = COALESCE(`rfc`, 'MAN160114EQ0'), `direccion` = COALESCE(`direccion`, 'Av. Paseo de Montejo Nº 494, entre las calles 43 y 45, Colonia Centro'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, NULL) WHERE `nombre_comercial` = 'Chariot';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Miguel Jesus Solis Martin'), `rfc` = COALESCE(`rfc`, 'SOMM8612107X3'), `direccion` = COALESCE(`direccion`, 'centro'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'hoteldelprado1@gmail.com') WHERE `nombre_comercial` = 'Prado';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Motel Sexto Sentido'), `rfc` = COALESCE(`rfc`, NULL), `direccion` = COALESCE(`direccion`, 'Calle 11 #323, colonia Santa Rita Cholu'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'motelsextosentido.facturas@gmail.com') WHERE `nombre_comercial` = 'Sexto';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Nimes Contract Services'), `rfc` = COALESCE(`rfc`, 'NCS2110253E8'), `direccion` = COALESCE(`direccion`, 'Km 37 de la Carretera Progreso–Telchac Puerto'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'GERENCIAPLAYAVIVA@GMAIL.COM') WHERE `nombre_comercial` = 'Playa Viva';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Olivia Guzman Duran'), `rfc` = COALESCE(`rfc`, 'GUDO510430L80'), `direccion` = COALESCE(`direccion`, 'Calle 37 480, por Alcalá Martín, C.P. 97050'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'oliviaguzmand@hotmail.com') WHERE `nombre_comercial` = 'Holly';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Operacion Hotelera Sensations'), `rfc` = COALESCE(`rfc`, 'CSE100629RB6'), `direccion` = COALESCE(`direccion`, '54 POR 47 Y 49 371-214 benito juarez'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, NULL) WHERE `nombre_comercial` = 'Crowne Plaza';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Operadora Hotel Colonial De Merida Sa De Cv'), `rfc` = COALESCE(`rfc`, 'OHC840522HT2'), `direccion` = COALESCE(`direccion`, NULL), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'contador@hotelcolonial.com.mx') WHERE `nombre_comercial` = 'Colonial';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Operadora Rcj Sa De Cv'), `rfc` = COALESCE(`rfc`, 'ORC160704BL9'), `direccion` = COALESCE(`direccion`, 'CALLE 59 POR 60 Y 62 502'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'melissa.olivas@corpover.mx') WHERE `nombre_comercial` = 'Nacional';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Prestadora De Servicios Yucateca'), `rfc` = COALESCE(`rfc`, 'PSY110407FK1'), `direccion` = COALESCE(`direccion`, 'Calle 59 #508, Centro, C.P. 97000, Mérida,'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'hreforma59@gmail.com') WHERE `nombre_comercial` = 'Reforma';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Santiago Vertiz Camara'), `rfc` = COALESCE(`rfc`, 'VECS800206NQ6'), `direccion` = COALESCE(`direccion`, 'Calle 63 575A, Centro, 97000 Mérida, Yucatán'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, NULL) WHERE `nombre_comercial` = 'Casa Querida';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Servicios Del Gobernador Merida'), `rfc` = COALESCE(`rfc`, 'SGM180816H98'), `direccion` = COALESCE(`direccion`, 'Calle 59 No. 535 por 66, Col. Centro, C.P.'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'roperia@gobernadormerida.com.mx;cuentaxpagar@gobernadormerida.com.mx') WHERE `nombre_comercial` = 'Gobernador';
UPDATE `cat_clientes` SET `razon_social` = COALESCE(`razon_social`, 'Servicios Turisticos La Mansion'), `rfc` = COALESCE(`rfc`, 'STM100109Q66'), `direccion` = COALESCE(`direccion`, 'Calle 59 No. 498 por 58 y 60, Centro, 97000'), `telefono` = COALESCE(`telefono`, NULL), `email_facturacion` = COALESCE(`email_facturacion`, 'contador@mansionmerida.com') WHERE `nombre_comercial` = 'Mansion';

-- =========================================================================
-- 2) DAR DE ALTA clientes nuevos (49)
-- =========================================================================

INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Agencia Midver Del Sur', 'Agencia Midver Del Sur', 'AMS1605134Y1', '59 ENTRE 66 Y 68 532 centro', NULL, 'olivia.vega@corpover.com.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Agencia Midver Del Sur') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AMS1605134Y1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Agroturismo Dzul Ha', 'Agroturismo Dzul Ha', 'ADH2203043F2', NULL, NULL, 'sotuta2022@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Agroturismo Dzul Ha') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'ADH2203043F2');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Almacen De Granos De La Peninsula', 'Almacen De Granos De La Peninsula', 'AGP060912NJ6', NULL, NULL, 'compras.alpensa@logra.com.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Almacen De Granos De La Peninsula') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AGP060912NJ6');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Amate Hospitalidad', 'Amate Hospitalidad', 'AHO250514IQA', '62 POR 49 Y 53 421 centro', NULL, 'amate62.contabilidad@outlook.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Amate Hospitalidad') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AHO250514IQA');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Arrendadora Ve Por Mas Sa De Cv, Sofom, Er., Grupo Financiero Ve Por Mas', 'Arrendadora Ve Por Mas Sa De Cv, Sofom, Er., Grupo Financiero Ve Por Mas', 'AVM950418QQ6', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Arrendadora Ve Por Mas Sa De Cv, Sofom, Er., Grupo Financiero Ve Por Mas') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AVM950418QQ6');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Bimbo', 'Bimbo', 'BIM011108DJ5', NULL, NULL, 'juanitho2@hotmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Bimbo') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'BIM011108DJ5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Caja Smg', 'Caja Smg', 'CSM830903GQ8', NULL, NULL, 'jdolores@cajasmg.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Caja Smg') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CSM830903GQ8');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Citriczyme', 'Citriczyme', 'CIT110208MY0', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Citriczyme') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CIT110208MY0');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Club De Playa Totem', 'Club De Playa Totem', 'CPT230331EA1', 'zona costera de Celestún, Yucatán', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Club De Playa Totem') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CPT230331EA1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Comercializadora La Chaya Maya S De Rl De Cv', 'Comercializadora La Chaya Maya S De Rl De Cv', 'CCM130418KF5', 'Calle 55 x 60 y 62, Centro Mérida, Yucatán', NULL, 'contabilidad@lachayamaya.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Comercializadora La Chaya Maya S De Rl De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CCM130418KF5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Conejo Corriendo S De Rl De Cv', 'Conejo Corriendo S De Rl De Cv', 'CCO210827216', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Conejo Corriendo S De Rl De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CCO210827216');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Controladora Hotelera Poh Sa De Cv', 'Controladora Hotelera Poh Sa De Cv', 'CHP170118NH4', 'Calle 5 B No. 290 A x 20 A y 60, Colonia Revolución', NULL, 'amafimer@posadas.com; comprasfimer@posadas.com;', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Controladora Hotelera Poh Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CHP170118NH4');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Coqui-Coqui Spa', 'Coqui-Coqui Spa', 'CSP030425F55', 'Calle 55 número 516, entre calles 62 y 64, Colonia Centro', NULL, 'merida@coquicoqui.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Coqui-Coqui Spa') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CSP030425F55');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Edith Areli Gongora Torres', 'Edith Areli Gongora Torres', 'GOTE950720U85', 'Calle 60 No. 285, entre las calles 23 y 25, en la colonia Alcalá Martín / Centro, Mérida', '9993503705', 'misolhahotel@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Edith Areli Gongora Torres') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'GOTE950720U85');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'El Yucateco Salsas Y Condimentos Sa De Cv', 'El Yucateco Salsas Y Condimentos Sa De Cv', 'YSC001117752', NULL, NULL, 'asistente@elyucateco.com;recursos.humanos@elyucateco.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'El Yucateco Salsas Y Condimentos Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'YSC001117752');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Fondo Harif', 'Fondo Harif', 'FHA190725TS5', NULL, NULL, 'unknownhotelmerida@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Fondo Harif') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'FHA190725TS5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Fundacion Teleton Mexico', 'Fundacion Teleton Mexico', 'FTM981104540', NULL, NULL, 'olalde@teleton.org.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Fundacion Teleton Mexico') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'FTM981104540');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Gastrolahe', 'Gastrolahe', 'GAS210323L59', NULL, NULL, 'cigarroavictoraul@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Gastrolahe') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'GAS210323L59');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Grupo Aldo De Mexico', 'Grupo Aldo De Mexico', 'GAM060726TJA', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Grupo Aldo De Mexico') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'GAM060726TJA');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Herdez', 'Herdez', 'HER8301121X4', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Herdez') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'HER8301121X4');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Hospitalidad Yucateca Sa De Cv', 'Hospitalidad Yucateca Sa De Cv', 'HYU231127BW1', 'Calle 62 No. 476 por 57 y 59, Centro, C.P. 97000', NULL, 'contador@hotelcolonial.com.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Hospitalidad Yucateca Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'HYU231127BW1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Hotel Brisas Wayam', 'Hotel Brisas Wayam', 'HBW241127U36', 'Av. Colón 508, García Ginerés, 97070', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Hotel Brisas Wayam') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'HBW241127U36');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Hoteles Del Camino', 'Hoteles Del Camino', 'HCA060831LN5', 'Avenida Prolongación Paseo de Montejo No. 128, por calles 29 y 31, Colonia México', NULL, 'auxadmin.merida@hoteleszar.com;gerencia.merida@hoteleszar.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Hoteles Del Camino') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'HCA060831LN5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Iglesia Principe De Paz De Cantamayec', 'Iglesia Principe De Paz De Cantamayec', 'IPP140127FR1', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Iglesia Principe De Paz De Cantamayec') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IPP140127FR1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Industrializadora Faddei', 'Industrializadora Faddei', 'IFA171213CM1', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Industrializadora Faddei') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IFA171213CM1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Aspira', 'Inmobiliaria Aspira', 'IAS130913GX3', 'Calle 60 #444 por 49 y 51, Colonia Centro,', NULL, 'proveedores@aluxes.com.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Aspira') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IAS130913GX3');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Hotelera Colonial', 'Inmobiliaria Hotelera Colonial', 'IHC130430B96', NULL, NULL, 'conta@hotelnacionalmerida.com;nacional.colonial@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Hotelera Colonial') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IHC130430B96');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Hotelera Montecristo', 'Inmobiliaria Hotelera Montecristo', 'IHM910524UB0', 'Carretera Progreso Telchac km 35.6, CP 97407, Telchac Puerto', NULL, 'contraloria@reefyucatan.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Hotelera Montecristo') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IHM910524UB0');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Merida', 'Inmobiliaria Merida', 'IME080508E58', 'Calle 60 No. 491, Colonia Centro, C.P. 97000, Mérida', NULL, 'egresos@hiexpressmerida.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Merida') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IME080508E58');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Meson De La Luna Sa De Cv', 'Inmobiliaria Meson De La Luna Sa De Cv', 'IML060418N47', 'Calle 26 No. 216, por 7 y 15, Fraccionamiento Altabrisa, C.P. 97133', NULL, 'contabilidad@mesondelaluna.com.mx;facturacion@mesondelaluna.com.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Meson De La Luna Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IML060418N47');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Inmobiliaria Sky De Yucatan Sa De Cv', 'Inmobiliaria Sky De Yucatan Sa De Cv', 'ISY1503108NA', NULL, NULL, 'manuel.can@hotelesprisma.com;jennifer.chan@hotelesprisma.com;cinthia.sosa@hotelesprisma.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Inmobiliaria Sky De Yucatan Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'ISY1503108NA');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Instituto Electoral Y De Participacion Ciudadana De Yucatan', 'Instituto Electoral Y De Participacion Ciudadana De Yucatan', 'IPE060524RD5', NULL, NULL, 'marissaaguilar@iepac.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Instituto Electoral Y De Participacion Ciudadana De Yucatan') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'IPE060524RD5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Jardin Services Yucatan', 'Jardin Services Yucatan', 'JSY170830Q32', 'Calle 59 #553 entre 68 y 70, Colonia Centro, C.P. 97000', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Jardin Services Yucatan') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'JSY170830Q32');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Los Andes Sa De Cv', 'Los Andes Sa De Cv', 'AND0706225IA', 'Carretera Mérida-Progreso Km 10.3, Tablaje 21074, Temozón Norte, 97302', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Los Andes Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AND0706225IA');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Luis Jorge Ancona Pasos', 'Luis Jorge Ancona Pasos', 'AOPL681127DF2', NULL, NULL, 'luisjorge22@hotmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Luis Jorge Ancona Pasos') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AOPL681127DF2');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Marianelia Castañeda Matos', 'Marianelia Castañeda Matos', 'CAMM861030132', NULL, NULL, 'mn.castaneda@hotmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Marianelia Castañeda Matos') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'CAMM861030132');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Marianna Navarrete Rosado', 'Marianna Navarrete Rosado', 'NARM8711045V5', NULL, NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Marianna Navarrete Rosado') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'NARM8711045V5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Municipio De Merida Yucatan', 'Municipio De Merida Yucatan', 'MMY981020E69', NULL, NULL, 'turisticavinculacion@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Municipio De Merida Yucatan') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'MMY981020E69');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Negocios Hoteleros Del Sureste Costa Del Sol', 'Negocios Hoteleros Del Sureste Costa Del Sol', 'NHS940701EZ0', 'Periférico Norte de Mérida', NULL, 'hotelcostadelsol21@hotmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Negocios Hoteleros Del Sureste Costa Del Sol') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'NHS940701EZ0');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Operadora Hotelera Hxa Sapi De Cv', 'Operadora Hotelera Hxa Sapi De Cv', 'OHH1906147H0', NULL, NULL, 'ap-xcanatun@angsana.com;Accounts-Xcanatun@angsana.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Operadora Hotelera Hxa Sapi De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'OHH1906147H0');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Operadora Nacional Hispana', 'Operadora Nacional Hispana', 'ONH970520T89', 'Calle 60 #346, C.P. 97000, Mérid', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Operadora Nacional Hispana') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'ONH970520T89');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Parks Hospitality Merida', 'Parks Hospitality Merida', 'PHM170118K74', 'BOSQUES DE DURAZNOS 127 PISO11', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Parks Hospitality Merida') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'PHM170118K74');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Partido Accion Nacional', 'Partido Accion Nacional', 'PAN400301JR5', NULL, NULL, 'facturaspan2015@hotmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Partido Accion Nacional') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'PAN400301JR5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Peninsulas Hospedaje', 'Peninsulas Hospedaje', 'PHO160513792', 'Avenida Paseo de Montejo #497, entre las calles 45 y 47, Colonia Centro,', NULL, 'gerencia@kaviapremium.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Peninsulas Hospedaje') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'PHO160513792');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Sandra Karina Aguayo Romero', 'Sandra Karina Aguayo Romero', 'AURS871018KJ5', 'C. 84-A POR 59 Y 59-A 500-M CENTRO', NULL, 'facturas.sandraaguayo@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Sandra Karina Aguayo Romero') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'AURS871018KJ5');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Secretaria De Administracion Y Finanzas', 'Secretaria De Administracion Y Finanzas', 'SHA840512SX1', NULL, NULL, 'beatriz.ek@yucatan.gob.mx', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Secretaria De Administracion Y Finanzas') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'SHA840512SX1');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Ucmace', 'Ucmace', 'UCM171116IGA', '33 POR 56 Y PASEO DE MONTEJO 496 CENTRO', NULL, 'cesarbe_0269@hotmail.com;rgranados@emered.mx;ramonlgp@hotmail.com;gwconsultores1@gmail.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Ucmace') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'UCM171116IGA');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Waxak Lajun Sa De Cv', 'Waxak Lajun Sa De Cv', 'WLA1604079I6', 'CALLE 3 POR 24 Y 60 #218 LOMA BONITA', NULL, 'annet.sabido@accor.com;ha7v8-gl@accor.com', 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Waxak Lajun Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'WLA1604079I6');
INSERT INTO `cat_clientes` (`nombre_comercial`, `razon_social`, `rfc`, `direccion`, `telefono`, `email_facturacion`, `estatus_credito`, `created_at`, `updated_at`) SELECT 'Wh Healthcare Sa De Cv', 'Wh Healthcare Sa De Cv', 'WHE240419RN3', '33 X PASE MONTEJO 496 MERIDA', NULL, NULL, 1, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `nombre_comercial` = 'Wh Healthcare Sa De Cv') AND NOT EXISTS (SELECT 1 FROM `cat_clientes` WHERE `rfc` = 'WHE240419RN3');

-- =========================================================================
-- POSIBLES DUPLICADOS -- revisar a mano, NO se tocaron automaticamente
-- =========================================================================
-- Estas filas del Excel se parecen a un cliente que ya existe, pero el
-- nombre/clave no coincide exacto, asi que se dieron de alta como
-- clientes NUEVOS en la seccion 2 en vez de fusionarse. Si en realidad
-- es la misma cuenta, borra el duplicado o renombralo desde
-- Catalogos > Clientes.
--   clave='CHAYAMAYA'            nombre='COMERCIALIZADORA LA CHAYA MAYA S DE RL DE CV'          parecido a: Chaya
--   clave='COQUISPA'             nombre='COQUI-COQUI SPA'                                       parecido a: Coqui
--   clave=None                   nombre='HOTEL BRISAS WAYAM'                                    parecido a: Brisas Wayam
--   clave='NACIONAL1'            nombre='INMOBILIARIA HOTELERA COLONIAL'                        parecido a: Colonial
--   clave='MESON'                nombre='INMOBILIARIA MESON DE LA LUNA SA DE CV'                parecido a: Meson de la Luna
--   clave='CAST'                 nombre='MARIANELIA CASTAÑEDA MATOS'                            parecido a: Castañeda
--   clave='COSTA'                nombre='NEGOCIOS HOTELEROS DEL SURESTE COSTA DEL SOL'          parecido a: Costa del Sol
--   clave='HOTELNH'              nombre='OPERADORA NACIONAL HISPANA'                            parecido a: NH o Nacional
--   clave='HOTELVIVA'            nombre='JARDIN SERVICES YUCATAN'                               parecido a: Viva o Playa Viva
--   clave='ZAR'                  nombre='HOTELES DEL CAMINO'                                    parecido a: Hotel Zar
--   clave='ALUXES'               nombre='INMOBILIARIA ASPIRA'                                   parecido a: Los Aluxes
--   clave='HOLIDAYINN'           nombre='INMOBILIARIA SKY DE YUCATAN SA DE CV'                  parecido a: Holiday
--   clave='DUBROVNIK'            nombre='LOS ANDES SA DE CV'                                    parecido a: Dubro
--   clave='FIESTAINN'            nombre='CONTROLADORA HOTELERA POH SA DE CV'                    parecido a: Fiesta
--   clave='FIESTAINNALTABRISA'   nombre='PARKS HOSPITALITY MERIDA'                              parecido a: Fiesta
--   clave='KAVIAPREMIUM'         nombre='PENINSULAS HOSPEDAJE'                                  parecido a: Kavia
--   clave='AMATE'                nombre='AMATE HOSPITALIDAD'                                    parecido a: Amate 61 y 62
